# Copyright (c) 2026 Zach Metcalf. All Rights Reserved.

name: Build

on:
  push:
    branches: [ main ]

jobs:
  # ----------------------------------------------------------------
  # Windows
  # ----------------------------------------------------------------

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # ----------------------------------------------------------------
      # Compiler
      # ----------------------------------------------------------------

      - name: Compiler
        uses: ilammy/msvc-dev-cmd@v1

      # ----------------------------------------------------------------
      # Configure
      # ----------------------------------------------------------------

      - name: Configure
        run: |
          cmake --preset demo-windows

      # ----------------------------------------------------------------
      # Build
      # ----------------------------------------------------------------

      - name: Build - Debug
        run: |
          cmake --build build --config Debug

      - name: Build - Release
        run: |
          cmake --build build --config Release

  # ----------------------------------------------------------------
  # Linux
  # ----------------------------------------------------------------

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ----------------------------------------------------------------
      # Configure
      # ----------------------------------------------------------------

      - name: Configure
        run: |
          cmake --preset demo-linux

      # ----------------------------------------------------------------
      # Build
      # ----------------------------------------------------------------

      - name: Build - Debug
        run: |
          cmake --build build --config Debug

      - name: Build - Release
        run: |
          cmake --build build --config Release
